### ISSUE TITLE
FrontEnd throwing error and not stat

### ISSUE THREAD

**Issue by hitzandy** [plaid/quickstart#195]
![image](https://user-images.githubusercontent.com/12350149/111659115-f67c0f80-8832-11eb-8b9f-d5b4e0705496.png)

D:\Projects\Payments\plaid_quickstart\quickstart\frontend\node_modules\terser-webpack-plugin\node_modules\p-limit\index.js:29
                } catch {}
                        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Projects\Payments\plaid_quickstart\quickstart\frontend\node_modules\terser-webpack-plugin\dist\index.js:24:38)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! plaid_react_quickstart@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the plaid_react_quickstart@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nex7dkq\AppData\Roaming\npm-cache\_logs\2021-03-18T16_16_40_975Z-debug.log

**Comment by hitzandy** [comment]
Please help.

**Comment by skylarmb** [comment]
hi @hitzandy what version of node are you using?

1. Make sure you are using node.js 14 (this repository is tested with v14.15.4)
2. delete your `node_modules` folder
3. run `npm install` again
4. try `npm start` again

**Comment by phoenixy1** [comment]
closing due to no response, if you are still having trouble please feel free to file a new issue

**Comment by hitzandy** [comment]
@skylarmb Thanks for the suggestions. It was some issue related to version, it started working with version 14, Thanks
