### ISSUE TITLE
Bug: python backend broken from fresh start

### ISSUE THREAD

**Issue by velicanu** [plaid/quickstart#349]
Following the instructions here: https://plaid.com/docs/quickstart/#setting-up-without-docker from a fresh python environment yields an `ImportError` when trying to start the python server. Exact steps to reproduce:
```bash
git clone https://github.com/plaid/quickstart.git
cd quickstart/python
# Copy the .env.example file to .env, then fill
# out PLAID_CLIENT_ID and PLAID_SECRET in .env
cp .env.example .env
virtualenv venv
source venv/bin/activate
pip3 install -r requirements.txt
./start.sh
```

Yields the following traceback:
```
Traceback (most recent call last):
  File "/Users/dragosvelicanu/test/quickstart/python/server.py", line 43, in <module>
    from flask import Flask
  File "/Users/dragosvelicanu/test/.direnv/python-3.10.3/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/Users/dragosvelicanu/test/.direnv/python-3.10.3/lib/python3.10/site-packages/jinja2/__init__.py)
Traceback (most recent call last):
  File "/Users/dragosvelicanu/test/quickstart/python/server.py", line 43, in <module>
    from flask import Flask
  File "/Users/dragosvelicanu/test/.direnv/python-3.10.3/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/Users/dragosvelicanu/test/.direnv/python-3.10.3/lib/python3.10/site-packages/jinja2/__init__.py)
```

I was able to fix this bumping the flask version in `requirements.txt` to:
```
flask==2.0.3
```

**Comment by phoenixy1** [comment]
I wasn't able to reproduce this, but it does seem to be a Thing (https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2) so submitted a PR to update this https://github.com/plaid/quickstart/pull/352/files
