### ISSUE TITLE
ensure quickstart is compatible with python3

### ISSUE THREAD

**Issue by michaelckelly** [plaid/quickstart#37]

**Comment by pau0line** [comment]
```
plim-mbp:python plim$ pip install -r requirements.txt
Collecting Flask==0.12 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/0e/e9/37ee66dde483dceefe45bb5e92b387f990d4f097df40c400cf816dcebaa4/Flask-0.12-py2.py3-none-any.whl
Collecting Jinja2==2.9.5 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/3c/d1/49d69bc23d0e0c7612248dd8f5391bd043648865132309616c280ca1c837/Jinja2-2.9.5-py2.py3-none-any.whl
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/c0/41/bae1254e0396c0cc8cf1751cb7d9afc90a602353695af5952530482c963f/MarkupSafe-0.23.tar.gz
Collecting Werkzeug==0.11.15 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/ef/c6/3c431fea5f93c8bc869ec9c7bdad9ffef4ff9c81bfe1d294217447206c46/Werkzeug-0.11.15-py2.py3-none-any.whl
Requirement already satisfied: click==6.7 in /anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 5)) (6.7)
Requirement already satisfied: itsdangerous==0.24 in /anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 6)) (0.24)
Collecting requests==2.13.0 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/7e/ac/a80ed043485a3764053f59ca92f809cc8a18344692817152b0e8bd3ca891/requests-2.13.0-py2.py3-none-any.whl
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/41/9e/309259ce8dff8c596e8c26df86dbc4e848b9249fd36797fd60be456f03fc/wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8d/71jb65yx25q3smy2mk8121gd1mw65c/T/pip-install-1h1rvk30/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/private/var/folders/8d/71jb65yx25q3smy2mk8121gd1mw65c/T/pip-install-1h1rvk30/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/8d/71jb65yx25q3smy2mk8121gd1mw65c/T/pip-install-1h1rvk30/wsgiref/
```
